modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="imperialweapons"
version="0.0.1"
displayName="Imperial Weapons"
credits="Created using mod maker MCreator"
displayURL="https://mcreator.net"
authors="Vox"

[[dependencies.imperialweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



